inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.0

# More readability
Naming/VariableNumber:
  EnforcedStyle: snake_case

# The test code is safe to evaluate
Security/Eval:
  Exclude:
    - 'testing/**/*'
