ENV['CUKE_COMMANDER_REPORT_FOLDER'] ||= "#{__dir__}/reports"
ENV['CUKE_COMMANDER_RSPEC_REPORT_NAME'] ||= 'rspec_report'
ENV['CUKE_COMMANDER_RSPEC_REPORT_HTML_FILE'] ||= "#{ENV['CUKE_COMMANDER_RSPEC_REPORT_NAME']}.html"
ENV['CUKE_COMMANDER_CUCUMBER_REPORT_NAME'] ||= 'cucumber_report'
ENV['CUKE_COMMANDER_CUCUMBER_REPORT_HTML_FILE'] ||= "#{ENV['CUKE_COMMANDER_CUCUMBER_REPORT_NAME']}.html"
